site_name: 'PPS-Unidad0-Tarea - Ruben_Garcia'
nav:
    - Home: index.md
    - Git: git.md
    - GitActions: gitActions.md
    - GitPages: gitPages.md
    - Docker: docker.md
    - Conclusiones: conclusiones.md
theme:
    name: material # Esto le da la apariencia moderna que se ve en el ejemplo
